language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - secure: RY5cUgIUpWjaFgNvs/yHnmxl1SjeijZKP6ys2BMXOgKxxb11IbkqyqwhqIWcEpOjWE81vgLtQAqOnrJn+3v5LH1Dy7icZo2BMCBxSRjRS4Tx1bWkcoMJ+P8lUk/+UvvX1voyhzlnGg6o4vXy5PjW5TEjEIW07rwdFh9RBnGg9xD0xIbP7jPniEQ4K9RiYZ1ZsFZhYIko/sxKrN54kOOXgpk9pwqGT1FUwCslxYFEgGGgba6N+9EZbG5e+QCY5YKx/QAqII6tCiTd50DQ5BKW5Y/KpwR9oluTYXgK51IEJOnYBjqtVFDZ7AT0tV5Fvv/rbytcfX1XGFsNSvTkNLLjOuoXIE86GEd3NQfCRi4nXoucbpLUYC8AQbjIZPoIFKFJA7tngVwnilEHrkOvZlWCEsqHb+hIyXQAxgSLr3jI8Jh+fvoNiIpcTo1pW8vVUuLV2EpuiIjXYl+d/x3jUuxo9i/yGFiUIHx1X6KPWHhDI5u507eTe77rl65gDMoG+ztMfMRmSQa7vNWRw7EdvnrV7CpZgW5jLjMnY51rsn4kDNKR4Dw7n2qIWor19ulm4T8Zuh6Ysut44CzGGK8qQhExyGBveil2mYWZSSK/L4JA+o4L/GkX3benMHb/IHoMVaLdjSw1E4qslkDcv8iPeE+Qvypc2my2W1cCfi5HnapRMao=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: "k5ZBPG5ngQV6mcMbqPebzV+jTGgpoaU1K9YVRpNEE/g0iuAzlrHJvlZc+Fiqd2/TJWpUDhFyz9a0yMUspyoRGKw7TplFMbooCmwSzRUXKxiuM05CkQINJR2Kum5Ixs+6V9lEANBROLbfxVmQEFIple7CQoxORl/QOPcYplSv3zYiHacJNSVFW/1uibYfkkitG/vzX8W9bxwU+X5L4wy1ns1Au5zMsnowhhNegTJLOD4fhB6ynsC9dhJQh3yisn3ZPqDy5iHzs2IJLE6BcdCAWmVImxhLfz8Ec5jD5iVlbyybYgLhS3bz7UoXTNtjV4HfAwRCh91+KtPIcrDrQFYzB4yqr9RZ0Ahf1hr/QydFYcOj6HE7UAfoR3MSbL8EIjltVTXSZORR1i8E41PrB1rjQATerA8Iq/OjRIII9EXYRXTYTbSsw6yC9rlzFyIzVAJj0qte21zpLG8Oh9MM9p3QDF/HCPZAvjk374wp7vBF6Det0wARlT6XDgt9w6aM9XJeVekYVNIBacYZTMuHlt5+xw0yW7Op9VBDEgg81dhSa1peglC3A87NzUrf58CeqTkMv/tI2FIvHb64UPf0e4kz5EOAZMly30u5xuoY846Ui5eS2u8WjLH+ELeJD2lMCiDAKxrArQ79iVJ8jifPQ1cytmRekB9T/3R+liy5V8m0YSE="
  bucket: form-service.octoblu.com
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: dist
  on:
    tags: true
