language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - secure: iWAcsHqf42KDrZ3eYelASUQ+QcbnKh948W018zZWPQIC/Ya6t1YT5xfqumTh8pu/x44IlsUQ32zFA7Jvbcpqgdhoo0guP9Dd45am5KLaxde2I68DdSvfZMuTJCYJ4LRNUeQJJWKK/FmRpgrUR6uv9SBSVgdloxYsplnQ0Tspxr9QEcheozbuTZYIpSvNgsVE2QQuYMQuazPbngVhu4fNQTbvyyUyzXOzPo9X9bFRnivynEUyYh3v8E++gubMDzWnIyNMUexIEDhA5hHy5k3YqE/uQtawcpBcL5f4e3nGtJSYg8k4igEx9cC14uZUCMMuJMFELlM4lewWft8x2yruXF6GIfWhmpSRxYs35C3QCLn1/H0podcloOe6wQHw/c6zpIJjUgY112vN2V0dk69q4O7nETHmAgoaqE+jqs2KLmc05mxM9Lg0H8n1JkeBoTcbM1Y5BQBXIj23hi1uWLqJhBtpWd3n092CYKYIkCFbcUTjen55VTe/N4v3q0qSRmH0c2IesSAvfa069ZXX0R4EEUDvambgDqoKOw+0dqCKAI69CGggVxtX6AA2eYDCnP8dSsYlEU0rmlbTfye/HxgenYruWMoqgzLR7xWoBdYFEBjDhZi5QXfM3B8MuAXF4kSzkZqypUnzlxQRF2e0T4U59yHqEkR6TcsEmYXkq1u/b88=
before_deploy:
- npm run build
- cp index.html dist
- for file in `find dist -type f`; do gzip --best $file && mv $file.gz $file; done
after_deploy:
- ./deploy/invalidate-cloudfront.sh $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TRAVIS_BRANCH
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: FjYnVrWYVuthp0wcKM+fxE8wMA0v4KbsAIahpfakHoUDaVV7I8Di+H+ibTFaOap8Sz070Rvg39lUC/R6hA0oiFqkQVXqSaU8RN8usRIy4GXzBxiYVsu9mnAJ6z6toNvkDQaJgtLNCQ7d6d6tSLhRwQy3Kj8i+gF1X+AFLHD89fOV0QysOkdjw7ZsCiv4xFkEZFoy/sD48dmjRiir64mgpZdj6+KjpLpYeLFUFtnTSi4Rbst9LVfsdlbc5P8d0LLsH3RIcAxatZ8vvXFueNBTp2d2TV4AKsglDCvts+sGdbGanfwv41vVnUvpV2Fj9UUx7b6QAp6YkUUrXcTg/tdCCsKbpQSRCISkGNYolNnhTMtClvEYGQcM2qil3Ln29jjzxPx7WE8+jTooGyXrBbho4bt6l0HWfqKoq1nJmGbXQMqamhIFZMHqfcJ6AzqM3fvGX5Q1M0Gg1yaqmHnXMuVTBeINCxdHAZiVNOHwodWZAKfNIznupXCGyUiJaSQmAjULK1fRZgHR+jjnSqXiW2/D6TW8rqKumbdKlqmp7j9cb4CXqirc19rCp0P0wWaLQvRMdbBKoB1gTGbsjzq5ZGv1fnPoSLVr52Nwm/cFl0/AcMfiPIvmLJir/rAtFjrWtxsde0gWS8wJq9ncHdxv4CJaTBheaFERbPUd2TFZcrx0Cck=
  bucket: form-service.octoblu.com
  region: us-west-2
  skip_cleanup: true
  detect_encoding: true
  local-dir: dist
  on:
    tags: true
